### ISSUE TITLE
data format

### ISSUE THREAD

**Issue by monperrus** [denishamann/OPL-Crash-Analysis#1]
version/bucket_numerical_id/trace
version/metadata.json <- date range, query date, Query URL, version diction{ <bucket_numerical_id> -> <bucket signature>}

**Comment by denishamann** [comment]
Updated the script that extracts data: https://github.com/denishamann/OPL-Crash-Analysis/commit/79c3f27b9a547c8496627ca3a83ed1101f42d488

Commited the extracted files with the desired data format: https://github.com/denishamann/OPL-Crash-Analysis/commit/a789c0370d1495c9c08f8fc40676fc17cce7ee14

**Comment by monperrus** [comment]
instead of a zip file, Json files browsable on github are better.

**Comment by denishamann** [comment]
Ok I changed it. It should be good now.
